{
 "title": "Vigil Backend Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Process CPU Seconds",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"vigil-backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{job=\"vigil-backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_size_bytes_count{job=\"vigil-backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{job=\"vigil-backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Resident Memory Bytes",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"vigil-backend\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}